/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prompts;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import frames.UtilFrame;
import main.ArrayManager;
import templates.Frame;
import templates.JErrorPane;
import utils.Shuffles;
import utils.Distributions;

/*
 * 
MIT License

Copyright (c) 2019 w0rthy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 *
 */

/**
 *
 * @author S630690
 */
final public class ArrayOptionsPrompt extends javax.swing.JFrame implements Frame {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    
    private ArrayManager ArrayManager;
    private JFrame Frame;
    private UtilFrame UtilFrame;
    
    /**
     * Creates new form SortPrompt
     */
    @SuppressWarnings("unchecked")
    public ArrayOptionsPrompt(ArrayManager ArrayManager, JFrame frame, UtilFrame utilFrame) {
        this.ArrayManager = ArrayManager;
        this.Frame = frame;
        this.UtilFrame = utilFrame;
        
        setAlwaysOnTop(true);
        setUndecorated(true);
        initComponents();
		jList1.setListData(ArrayManager.getDistributionIDs());
        for(int i = 0; i < ArrayManager.getDistributions().length; i++) {
            if(ArrayManager.getDistribution().equals(ArrayManager.getDistributions()[i])) {
                jList1.setSelectedIndex(i);
                break;
            }
        }
        jList2.setListData(ArrayManager.getShuffleIDs());
        for(int i = 0; i < ArrayManager.getShuffles().length; i++) {
            if(ArrayManager.getShuffle().equals(ArrayManager.getShuffles()[i])) {
                jList2.setSelectedIndex(i);
                break;
            }
        }
		jCheckBox1.setSelected(ArrayManager.isBackwards());
        reposition();
        setVisible(true); 
    }

    @Override
    public void reposition() {
        setLocation(Frame.getX()+(Frame.getWidth()-getWidth())/2,Frame.getY()+(Frame.getHeight()-getHeight())/2);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
		this.jLabel1 = new javax.swing.JLabel();
        this.jLabel2 = new javax.swing.JLabel();
        this.jScrollPane1 = new javax.swing.JScrollPane();
        this.jList2 = new javax.swing.JList();
        this.jScrollPane2 = new javax.swing.JScrollPane();
        this.jList1 = new javax.swing.JList();
		this.jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Set");
        jLabel2.setText("Shuffle");
		
        jCheckBox1.setText("Backwards");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jCheckBox1ActionPerformed();
				} catch(Exception e) {
					e.printStackTrace();
				}
            }
        });


        jScrollPane1.setViewportView(this.jList1);
		jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				try {
					jList1ValueChanged(evt);
				} catch(Exception e) {
					e.printStackTrace();
				}
            }
        });

		jScrollPane2.setViewportView(this.jList2);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				try {
					jList2ValueChanged(evt);
				} catch(Exception e) {
					e.printStackTrace();
				}
            }
        });
		
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(this.jLabel1)
                        .addGap(104, 104, 104)
                        .addComponent(this.jLabel2)
                        .addGap(35, 35, 35))
                .addGroup(layout.createSequentialGroup()
                        .addComponent(this.jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(this.jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(this.jCheckBox1))
				);
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(this.jLabel1)
                                .addComponent(this.jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(this.jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(this.jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(this.jCheckBox1)
                        .addGap(0, 0, 0))
                );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	private void jCheckBox1ActionPerformed() {//GEN-FIRST:event_jCheckBox2ActionPerformed
        ArrayManager.toggleBackwardsData(jCheckBox1.isSelected());
    }//GEN-LAST:event_jCheckBox1ActionPerformed
	
	private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) throws Exception {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        int selection = jList1.getSelectedIndex();
        switch (selection) {
        case 0:
            ArrayManager.setDistribution(ArrayManager.getDistributions()[0]);
            break;
        case 1:
            ArrayManager.setDistribution(ArrayManager.getDistributions()[1]);
            break;
        case 2:
            ArrayManager.setDistribution(ArrayManager.getDistributions()[2]);
            break;
		case 3:
            ArrayManager.setDistribution(ArrayManager.getDistributions()[3]);
            break;
		case 4:
            ArrayManager.setDistribution(ArrayManager.getDistributions()[4]);
            break;
        case 5:
            ArrayManager.setDistribution(ArrayManager.getDistributions()[5]);
            break;
        case 6:
            ArrayManager.setDistribution(ArrayManager.getDistributions()[6]);
            break;
		case 7:
            ArrayManager.setDistribution(ArrayManager.getDistributions()[7]);
            break;
		case 8:
            ArrayManager.setDistribution(ArrayManager.getDistributions()[8]);
            break;
		case 9:
            ArrayManager.setDistribution(ArrayManager.getDistributions()[9]);
            break;
        default:
            break;
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) throws Exception {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        int selection = jList2.getSelectedIndex();
        switch (selection) {
        case 0:
            ArrayManager.setShuffle(ArrayManager.getShuffles()[0]);
            break;
        case 1:
            ArrayManager.setShuffle(ArrayManager.getShuffles()[1]);
            break;
        case 2:
            ArrayManager.setShuffle(ArrayManager.getShuffles()[2]);
            break;
        case 3:
            ArrayManager.setShuffle(ArrayManager.getShuffles()[3]);
            break;
		case 4:
            ArrayManager.setShuffle(ArrayManager.getShuffles()[4]);
            break;
        case 5:
            ArrayManager.setShuffle(ArrayManager.getShuffles()[5]);
            break;
        case 6:
            ArrayManager.setShuffle(ArrayManager.getShuffles()[6]);
            break;
		case 7:
            ArrayManager.setShuffle(ArrayManager.getShuffles()[7]);
            break;
		case 8:
            ArrayManager.setShuffle(ArrayManager.getShuffles()[8]);
            break;
		case 9:
            ArrayManager.setShuffle(ArrayManager.getShuffles()[9]);
            break;
        default:
            break;
        }
    }//GEN-LAST:event_jList1ValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    @SuppressWarnings("rawtypes")
    private javax.swing.JList jList1;
    @SuppressWarnings("rawtypes")
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables
}